name: CML Performance Check
on:
  push:

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -U klib
          pip install -r requirements.txt
          python klib/scripts/performance.py

          cml-publish klib/scripts/boxplots.png --md >> report.md
          cml-send-comment report.md